version: '2'

services:

  drupal:
    image: sastoo/drupal:latest
    ports:
      - 80:80
    volumes:
      -  /Users/kenpatolia/upenn_local/sites:/var/www/sites
      -  /Users/kenpatolia/upenn_local/profiles:/var/www/profiles
      -  db_data:/var/lib/mysql:/var/lib/mysql
 #   # this takes advantage of the feature in Docker that a new anonymous
    #   # volume (which is what we're creating here) will be initialized with the
    #   # existing content of the image at the same location
    #   -  /home/ubuntu/new.sql:/var/www/new.sql
    restart: always
    volumes:
      db_data:
